name: Package
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
jobs:
  package-windows-x86:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          architecture: 'x64'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          chmod +x ./gradlew
          ./gradlew :generateComposeResClass
          ./gradlew :generateResourceAccessorsForComposeMain
          ./gradlew :generateExpectResourceCollectorsForCommonMain
          ./gradlew :generateActualResourceCollectorsForComposeJvmMain
          ./gradlew :assembleComposeJvmMainResources
      - name: package windowsUberJar
        run: ./gradlew :packageReleaseUberJarForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-windows-uberjar-amd64
          path: build/compose/jars/*
      - name: package windowsAppImage
        run: ./gradlew :packageReleaseAppImage
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-windows-portable-amd64
          path: build/compose/binaries/main/app/*
      - name: package windowsMsi
        run: ./gradlew :packageReleaseMsi
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-windows-installer-msi-amd64
          path: build/compose/binaries/main/msi/*
      - name: package windowsExe
        run: ./gradlew :packageReleaseExe
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-windows-installer-exe-amd64
          path: build/compose/binaries/main/exe/*
  package-windows-arm:
    runs-on: windows-11-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          architecture: 'aarch64'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          chmod +x ./gradlew
          ./gradlew :generateComposeResClass
          ./gradlew :generateResourceAccessorsForComposeMain
          ./gradlew :generateExpectResourceCollectorsForCommonMain
          ./gradlew :generateActualResourceCollectorsForComposeJvmMain
          ./gradlew :assembleComposeJvmMainResources
      - name: package windowsUberJar
        run: ./gradlew :packageReleaseUberJarForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-windows-uberjar-aarch64
          path: build/compose/jars/*
      - name: package windowsAppImage
        run: ./gradlew :packageReleaseAppImage
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-windows-portable-aarch64
          path: build/compose/binaries/main/app/*
      - name: package windowsMsi
        run: ./gradlew :packageReleaseMsi
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-windows-installer-msi-aarch64
          path: build/compose/binaries/main/msi/*
      - name: package windowsExe
        run: ./gradlew :packageReleaseExe
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-windows-installer-exe-aarch64
          path: build/compose/binaries/main/exe/*
  package-linux-x86:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          architecture: 'x64'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          chmod +x ./gradlew
          ./gradlew :generateComposeResClass
          ./gradlew :generateResourceAccessorsForComposeMain
          ./gradlew :generateExpectResourceCollectorsForCommonMain
          ./gradlew :generateActualResourceCollectorsForComposeJvmMain
          ./gradlew :assembleComposeJvmMainResources
      - name: package linuxUberJar
        run: ./gradlew :packageReleaseUberJarForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-linux-uberjar-amd64
          path: build/compose/jars/*
      - name: package linuxAppImage
        run: ./gradlew :packageReleaseAppImage
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-linux-portable-amd64
          path: build/compose/binaries/main/app/*
      - name: package linuxDeb
        run: ./gradlew :packageReleaseDeb
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-linux-installer-deb-amd64
          path: build/compose/binaries/main/deb/*
      - name: package linuxRpm
        run: ./gradlew :packageReleaseRpm
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-linux-installer-rpm-amd64
          path: build/compose/binaries/main/rpm/*
  package-linux-arm:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          architecture: 'aarch64'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          chmod +x ./gradlew
          ./gradlew :generateComposeResClass
          ./gradlew :generateResourceAccessorsForComposeMain
          ./gradlew :generateExpectResourceCollectorsForCommonMain
          ./gradlew :generateActualResourceCollectorsForComposeJvmMain
          ./gradlew :assembleComposeJvmMainResources
      - name: package linuxUberJar
        run: ./gradlew :packageReleaseUberJarForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-linux-uberjar-aarch64
          path: build/compose/jars/*
      - name: package linuxAppImage
        run: ./gradlew :packageReleaseAppImage
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-linux-portable-aarch64
          path: build/compose/binaries/main/app/*
      - name: package linuxDeb
        run: ./gradlew :packageReleaseDeb
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-linux-installer-deb-aarch64
          path: build/compose/binaries/main/deb/*
      - name: package linuxRpm
        run: ./gradlew :packageReleaseRpm
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-linux-installer-rpm-aarch64
          path: build/compose/binaries/main/rpm/*
  package-macos-arm:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          architecture: 'aarch64'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          chmod +x ./gradlew
          ./gradlew :generateComposeResClass
          ./gradlew :generateResourceAccessorsForComposeMain
          ./gradlew :generateExpectResourceCollectorsForCommonMain
          ./gradlew :generateActualResourceCollectorsForComposeJvmMain
          ./gradlew :assembleComposeJvmMainResources
      - name: package macosUberJar
        run: ./gradlew :packageReleaseUberJarForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-macos-uberjar-aarch64
          path: build/compose/jars/*
      - name: package macosDmg
        run: ./gradlew :packageReleaseDmg
      - uses: actions/upload-artifact@v4
        with:
          name: MCL-macos-installer-dmg-aarch64
          path: build/compose/binaries/main/dmg/*