name: Package
on:
  release:
    types: [ created ]
jobs:
  package-windows:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          chmod +x ./gradlew
          ./gradlew :assembleJvmMainResources
      - name: package windowsUberJar
        run: ./gradlew :packageUberJarForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: windowsUberJar
          path: build/compose/jars/*
      - name: package windowsAppImage
        run: ./gradlew :packageAppImage
      - uses: actions/upload-artifact@v4
        with:
          name: windowsAppImage
          path: build/compose/binaries/main/app/*
      - name: package windowsMsi
        run: ./gradlew :packageMsi
      - uses: actions/upload-artifact@v4
        with:
          name: windowsMsi
          path: build/compose/binaries/main/msi/*
      - name: package windowsExe
        run: ./gradlew :packageExe
      - uses: actions/upload-artifact@v4
        with:
          name: windowsExe
          path: build/compose/binaries/main/exe/*
  package-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          chmod +x ./gradlew
          ./gradlew :assembleJvmMainResources
      - name: package linuxUberJar
        run: ./gradlew :packageUberJarForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: linuxUberJar
          path: build/compose/jars/*
      - name: package linuxAppImage
        run: ./gradlew :packageAppImage
      - uses: actions/upload-artifact@v4
        with:
          name: linuxAppImage
          path: build/compose/binaries/main/app/*
      - name: package linuxDeb
        run: ./gradlew :packageDeb
      - uses: actions/upload-artifact@v4
        with:
          name: linuxDeb
          path: build/compose/binaries/main/deb/*
      - name: package linuxRpm
        run: ./gradlew :packageRpm
      - uses: actions/upload-artifact@v4
        with:
          name: linuxRpm
          path: build/compose/binaries/main/rpm/*
  package-macos:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          chmod +x ./gradlew
          ./gradlew :assembleJvmMainResources
      - name: package macosUberJar
        run: ./gradlew :packageUberJarForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: macosUberJar
          path: build/compose/jars/*
      - name: package macosDmg
        run: ./gradlew :packageDmg
      - uses: actions/upload-artifact@v4
        with:
          name: macosDmg
          path: build/compose/binaries/main/dmg/*